### ISSUE TITLE
is_table_name : true  最新版本无效没有生成列名

### ISSUE THREAD

**Issue by siyue8899** [xxjwxc/gormt#109]
go get -u -v github.com/xxjwxc/gormt@master
生成出来的不带列名了
```yml
base:
    is_dev : false
out_dir : ./model  # 输出目录
url_tag : json # web url tag(json,db(https://github.com/google/go-querystring))
language :  # 语言(English,中 文)
db_tag : gorm # 数据库标签(gorm,db)
simple : false # 简单输出(默认gorm标签不输出)
is_out_sql : true # 是否输出 sql 原信息
is_out_func : false # 是否输出 快捷函数
is_web_tag : true # 是否打web标记(json标记前提条件)
is_web_tag_pk_hidden: true # web标记是否隐藏主键
is_foreign_key : false # 是否导出外键关联
is_gui : false # 是否ui模式显示
is_table_name : true # 是否直接生成表名,列名
is_null_to_point : false # 数据库默认 'DEFAULT NULL' 时设置结构为指针类型
table_prefix : "" # 表前缀, 如果有则使用, 没有留空
db_info:
    host :
    port : 3306
    username : 
    password :
    database : 
    type: 0 # 数据库类型:0:mysql , 1:sqlite ,  #2:mssql
```
